# Site settings
title: deferred.io
author_name: Michael Turquette
email: mturquette@deferred.io
description: > # this means to ignore newlines until "baseurl:"
  This is where I flush my I/O buffer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://deferred.io" # the base hostname & protocol for your site
twitter_username: mturquette
github_username:  mturquette

# Build settings
markdown: rdiscount
